# Generated by Django 6.0.7 on 2026-07-17 16:58

import django.db.models.deletion
import specialists.models
import specialists.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpecialistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=specialists.models.photo_upload_path, validators=[specialists.validators.validate_photo])),
                ('photo_thumbnail', models.ImageField(blank=True, null=True, upload_to=specialists.models.photo_upload_path)),
                ('academic_degree', models.CharField(choices=[('none', "Yo'q"), ('phd', 'PhD'), ('dsc', 'DSc'), ('candidate_legacy', 'Fan nomzodi (eski tizim)'), ('doctor_legacy', 'Fan doktori (eski tizim)')], default='none', max_length=20)),
                ('academic_title', models.CharField(choices=[('none', "Yo'q"), ('senior_researcher', 'Katta ilmiy xodim'), ('docent', 'Dotsent'), ('professor', 'Professor'), ('academician', 'Akademik')], default='none', max_length=20)),
                ('position', models.CharField(blank=True, choices=[('junior_researcher', 'Kichik ilmiy xodim'), ('senior_researcher', 'Katta ilmiy xodim'), ('leading_researcher', 'Yetakchi ilmiy xodim'), ('chief_researcher', 'Bosh ilmiy xodim'), ('lab_head', 'Laboratoriya mudiri'), ('department_head', "Bo'lim boshlig'i")], max_length=30)),
                ('research_interests', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True, help_text="Ochiq bo'lsa va tasdiqlangan bo'lsa, qidiruvda ko'rinadi.")),
                ('moderation_status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialists', to='specialists.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialistDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=specialists.models.document_upload_path, validators=[specialists.validators.validate_uploaded_document])),
                ('original_filename', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='specialists.specialistprofile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
