# Generated by Django 6.0.7 on 2026-07-20 23:59

import django.db.models.deletion
import specialists.models
import specialists.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialistprofile',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ScientificWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('foreign_article', 'Xorijiy maqola'), ('local_article', 'Mahalliy maqola'), ('thesis', 'Tezis'), ('patent', 'Patent'), ('monograph', 'Monografiya')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('authorship', models.CharField(blank=True, choices=[('main_author', 'Asosiy muallif'), ('co_author', 'Hammuallif')], max_length=20)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True, max_length=500)),
                ('doi', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to=specialists.models.work_upload_path, validators=[specialists.validators.validate_uploaded_document])),
                ('original_filename', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('index_type', models.CharField(blank=True, choices=[('scopus', 'Scopus'), ('wos', 'Web of Science'), ('scopus_wos', 'Scopus & WoS'), ('other_intl', 'Boshqa xalqaro')], max_length=20)),
                ('impact_factor', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('journal_name', models.CharField(blank=True, max_length=255)),
                ('thesis_category', models.CharField(blank=True, choices=[('international_conf', 'Xalqaro konferensiya'), ('republic_conf', 'Respublika konferensiyasi')], max_length=30)),
                ('patent_category', models.CharField(blank=True, choices=[('invention', 'Ixtiro'), ('utility_model', 'Foydali model'), ('industrial_design', 'Sanoat namunasi'), ('software_cert', 'EHM dasturi guvohnomasi')], max_length=30)),
                ('patent_type', models.CharField(blank=True, choices=[('local', 'Mahalliy'), ('foreign', 'Xorijiy')], max_length=20)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=50)),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='specialists.specialistprofile')),
            ],
            options={
                'ordering': ['-year', '-created_at'],
            },
        ),
    ]
