# Generated by Django 6.0.7 on 2026-07-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialistprofile',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
