# Generated by Django 6.0.7 on 2026-07-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0002_alter_specialistprofile_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialistprofile',
            name='academic_degree',
            field=models.CharField(choices=[('none', "Yo'q"), ('bachelor', 'Bakalavr'), ('master', 'Magistr'), ('phd', 'PhD'), ('dsc', 'DSc'), ('candidate_legacy', 'Fan nomzodi'), ('doctor_legacy', 'Fan doktori')], default='none', max_length=20),
        ),
    ]
