# Generated by Django 6.0.7 on 2026-07-21 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0003_migrate_documents_to_works'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpecialistDocument',
        ),
    ]
