# Generated by Django 6.0.7 on 2026-07-21 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0003_alter_specialistprofile_academic_degree'),
        ('specialists', '0004_delete_specialistdocument'),
    ]

    operations = [
    ]
